### ISSUE TITLE
What is it good for?

### ISSUE THREAD

**Issue by MartinThoma** [TehMillhouse/PyMarkovChain#13]
What can PyMarkovChain do?

It seems to me that this project is not continued. What do you think about [removing the package from PyPI](http://stackoverflow.com/a/20403468/562769)?

**Comment by asmeurer** [comment]
WAT

**Comment by TehMillhouse** [comment]
It's admittedly misnamed, but it does have functionality: It's a simple random text generator. Just because it's not being actively expanded doesn't mean people don't find it useful. I'm closing this because WAT indeed.

**Comment by gvanderheide** [comment]
You would suspect that this is a general package for analyzing/solving Markov chains, but it is a very specialized package for generating text. Can you not rename it to something more appropriate?

**Comment by masnick** [comment]
Agreed, this should be renamed.
