### ISSUE TITLE
pypi behind the times

### ISSUE THREAD

**Issue by kylerbrown** [TehMillhouse/PyMarkovChain#14]
Is the current master of PyMarkovChain stable enough to add to pypi? I found the argument `n` useful in the MarkovChain initialization. Thanks!

**Comment by TehMillhouse** [comment]
Sorry for taking so long to notice this. I've pushed the current HEAD to PyPI.

**Comment by asmeurer** [comment]
Glad you found that feature useful. 

You may also want to tag your release points in git.
